- hosts: localhost
  gather_facts: no

  vars:
    application_directory: /tmp/application

  tasks:
    - name: Create application directory
      file:
        path: "{{application directory}}"
        state: directory
        mode: 0755

    - name: Get latest git version
      git:
        repo: git@github.com:boyanaboneva/devops-programme
        dest: "{{application directory}}"
        version: main
        force: yes

    - name: Install dependencies
      pip:
        requirements: "{{application directory}}"/requirements.txt
        virtualenv: "{{application directory}}"/venv

    - name: Run unit tests
      ansible.legacy.command: python -m unittest app_test.py
      args:
        chdir: "{{application directory}}"/app
      register: test_result
