name: workflow that triggers on pull request.
run-name: ${{ github.actor }} workflow that triggers on pull request
on:
  pull_request:
    branches:
      - main
jobs:
  production-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.12]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed .md files
        id: changed-files-specific
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **.md

      - name: Run step if file changed
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: flake8
          python-version: ${{ matrix.python-version }}