name: Flask App GitHub Actions Pipeline
run-name: ${{ github.actor }} workflow that triggers on push to a feature branch and perform check on a Flask app repo

on:
  push:
    branches:
      - feature/M1-4-2-CI-Practice
  pull_request:
    branches:
      - main

jobs:
  scan:
    name: GitLeaks scan for secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  editorconfig:
    name: EditorConfig Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker
