name: Flask App GitHub Actions Pipeline
run-name: Flask App GitHub Actions Pipeline

on:
  push:
    branches:
      - feature/M1-4-2-CI-Practice
  pull_request:
    branches:
      - main

jobs:
  gitleaks-scan:
    name: GitLeaks scan for secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  editorconfig:
    name: EditorConfig Checker
    runs-on: ubuntu-latest
    needs: gitleaks-scan
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  python-pylint:
    name: Executes pylint
    runs-on: ubuntu-latest
    needs: gitleaks-scan
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Lint
        uses: gabriel-milan/action-pylint@v1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} # GitHub token
          path: "./*.py" # Glob pattern for files to lint
          fail: true # Fail the action if pylint errors are found
          pr-message: true # Send a PR message if pylint errors are found

  python-black:
    name: Python Black
    runs-on: ubuntu-latest
    needs: gitleaks-scan
    steps:
      - uses: actions/checkout@v3
      - name: Python Black
        uses: cytopia/docker-black@0.8

  markdownlint-cli:
    name: Markdownlint CLI
    runs-on: ubuntu-latest
    needs: gitleaks-scan
    steps:
      - name: Install Markdownlint CLI
        run: npm install -g markdownlint-cli

      - name: Run Markdownlint
        run: markdownlint **/*.md

